version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - VITE_API_BASE_URL=http://localhost:5000

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: mongodb://mongo:27017/medicluster
      ML_ENGINE_URL: http://ml-engine:8000
      PORT: 5000
    depends_on:
      - mongo
      - ml-engine

  ml-engine:
    build: ./ml-engine
    ports:
      - "8000:8000"

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
